[toolchain]
anchor_version = "0.31.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
pm15 = "EEeQgeh56xge6y82xU9K8sb2PfPs9nXHh3fHrNEwdcrU"

[programs.mainnet]
pm15 = "EEeQgeh56xge6y82xU9K8sb2PfPs9nXHh3fHrNEwdcrU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/pm15"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"
